name: Sync Orders

on:
   # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run sync-orders script
        run: |
          echo "Starting orders synchronization..."
          echo "VITE_SUPABASE_URL is set: ${{ env.VITE_SUPABASE_URL != '' }}"
          echo "VITE_SUPABASE_ANON_KEY is set: ${{ env.VITE_SUPABASE_ANON_KEY != '' }}"
          node scripts/sync-orders.cjs
          echo "Orders synchronization completed" 
