name: Sync Orders

on:
  schedule:
    - cron: '*/5 * * * *'  # Alle 5 Minuten
  workflow_dispatch:  # Ermöglicht manuelle Ausführung

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup environment variables
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

      - name: Run sync-orders script
        run: |
          echo "Starting orders synchronization..."
          node scripts/sync-orders.cjs
          echo "Orders synchronization completed" 